### ISSUE TITLE
รายงานความเสี่ยง

### ISSUE THREAD

**Issue by infogamethai** [MicrosoftDocs/Contribute.th-TH#1]
[ป้อนคำติชมที่นี่]

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [ภาพรวมคู่มือผู้ร่วมสร้าง Microsoft Docs - Contributor Guide](https://docs.microsoft.com/th-th/contribute/)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.th-th/blob/live/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @gamethi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
สวัสดี @infogamethai  

เราขอขอบคุณสำหรับความคิดเห็นของคุณและเรามุ่งมั่นเพื่อจะพัฒนาประสบการณ์ของคุณใน docs.microsoft.com อย่างไรก็ตาม เราต้องการข้อมูลของคุณเพิ่มเติมเพื่อให้สามารถดำเนินการคำติชมของคุณได้ โปรดให้ข้อมูลอย่างละเอียดเพิ่มเติมและทำให้ความคิดเห็นของคุณมีความชัดเจนได้หรือไม่ 

ขอแสดงความนับถือ 
ทีม Microsoft DOCS International

**Comment by V-vafune** [comment]
สวัสดี @infogamethai  

เรากำลังติดตามความคิดเห็นของคุณก่อนหน้านี้ อย่างไรก็ตาม เราต้องการข้อมูลของคุณเพิ่มเติมเพื่อให้สามารถดำเนินการคำติชมของคุณได้ โปรดให้ข้อมูลอย่างละเอียดเพิ่มเติมและทำให้ความคิดเห็นของคุณมีความชัดเจนได้หรือไม่ 

ขอแสดงความนับถือ 

ทีม Microsoft DOCS International

**Comment by CeciAc** [comment]
สวัสดี @infogamethai
ขอขอบคุณอีกครั้งสำหรับความคิดเห็นของคุณ
ขออภัย เรายังขาดข้อมูลอยู่และเราไม่สามารถดำเนินการคำติชมของคุณได้ เรากำลังปิดปัญหา GitHub ในขณะนี้ แต่เราขอแนะนำให้คุณส่งคำติชมเพิ่มเติมในอนาคต
ขอแสดงความนับถือ
ทีม Microsoft DOCS International
